### ISSUE TITLE
Attempting to build on UE4 4.12.5

### ISSUE THREAD

**Issue by crimsonstrife** [fathurahman/game-modules#1]
So I'm trying to build these as plugins, and it could just be the version of the engine I'm using, but I get a lot of errors, but the most notable ones are about files that are being referenced that don't exist.

For the record I'm still kinda new to C++ and was just taking a crack at this.  I created blank plugins by the same names as each module, then put them in the source folder and attempted to build.

Any help would be appreciated! Thanks

`B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(15): error C2027: use of undefined type 'UClass'
2>  a:\program files (x86)\epic games\4.12\engine\source\runtime\core\public\UObject/UObjectHierarchyFwd.h(39): note: see declaration of 'UClass'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(15): error C2065: 'ClassConstructorType': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(15): error C2059: syntax error: '<template-id>'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(19): error C2144: syntax error: 'UClass' should be preceded by ';'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(19): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(36): error C2027: use of undefined type 'UClass'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(22): note: see declaration of 'UClass'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(36): error C2227: left of '->ClassFlags' must point to class/struct/union/generic type
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(38): error C2664: 'void UObjectForceRegistration(UObjectBase *)': cannot convert argument 1 from 'UClass *' to 'UObjectBase *'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(38): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(39): error C2027: use of undefined type 'UClass'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(22): note: see declaration of 'UClass'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(39): error C2227: left of '->ClassFlags' must point to class/struct/union/generic type
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(43): error C2065: 'GUIWidgetClass': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(43): error C2275: 'UGUIWidgetFactory': illegal use of this type as an expression
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Source\GameUIEd\Public/GUIWidgetFactory.h(9): note: see declaration of 'UGUIWidgetFactory'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(43): error C3861: 'CPP_PROPERTY_BASE': identifier not found
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(43): error C2027: use of undefined type 'UClass'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(22): note: see declaration of 'UClass'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(43): error C3861: 'StaticClass': identifier not found
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(43): error C2027: use of undefined type 'UClassProperty'
2>  a:\program files (x86)\epic games\4.12\engine\source\runtime\core\public\UObject/UObjectHierarchyFwd.h(25): note: see declaration of 'UClassProperty'
2>  a:\program files (x86)\epic games\4.12\engine\source\runtime\core\public\UObject/UObjectHierarchyFwd.h(25): note: see declaration of 'UClassProperty'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(45): error C2027: use of undefined type 'UClass'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(22): note: see declaration of 'UClass'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(45): error C2227: left of '->StaticLink' must point to class/struct/union/generic type
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(47): error C2065: 'UMetaData': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(47): error C2065: 'MetaData': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(47): error C2027: use of undefined type 'UClass'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(22): note: see declaration of 'UClass'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(47): error C2227: left of '->GetOutermost' must point to class/struct/union/generic type
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(47): error C2227: left of '->GetMetaData' must point to class/struct/union/generic type
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(48): error C2065: 'MetaData': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(48): error C2227: left of '->SetValue' must point to class/struct/union/generic type
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(48): note: type is 'unknown-type'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(49): error C2065: 'MetaData': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(49): error C2227: left of '->SetValue' must point to class/struct/union/generic type
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(49): note: type is 'unknown-type'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(50): error C2065: 'MetaData': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(50): error C2227: left of '->SetValue' must point to class/struct/union/generic type
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(50): note: type is 'unknown-type'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(51): error C2065: 'MetaData': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(51): error C2227: left of '->SetValue' must point to class/struct/union/generic type
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(51): note: type is 'unknown-type'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(52): error C2065: 'MetaData': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(52): error C2227: left of '->SetValue' must point to class/struct/union/generic type
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(52): note: type is 'unknown-type'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(56): error C2027: use of undefined type 'UClass'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(22): note: see declaration of 'UClass'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(56): error C2227: left of '->GetClass' must point to class/struct/union/generic type
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(66): error C2065: 'CastChecked': undeclared identifier
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(66): error C2275: 'UPackage': illegal use of this type as an expression
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(23): note: see declaration of 'UPackage'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(66): error C2027: use of undefined type 'UPackage'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(23): note: see declaration of 'UPackage'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(66): error C3861: 'StaticClass': identifier not found
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(67): error C2027: use of undefined type 'UPackage'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(23): note: see declaration of 'UPackage'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(67): error C2227: left of '->SetPackageFlags' must point to class/struct/union/generic type
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(73): error C2027: use of undefined type 'UPackage'
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(23): note: see declaration of 'UPackage'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Intermediate\Build\Win64\UE4Editor\Inc\GameUIEd\GameUIEd.generated.cpp(73): error C2227: left of '->SetGuid' must point to class/struct/union/generic type
2>  Module.GameUI.cpp
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUI\Source\GameUI\Private/GameUIPrivatePCH.h(15): fatal error C1083: Cannot open include file: 'GameModule.h': No such file or directory
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Source\GameUIEd\Public\GameUIEd.h(4): error C2011: 'IGameUIEdModule': 'class' type redefinition
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Source\GameUIEd\Public\GameUIEd.h(4): note: see declaration of 'IGameUIEdModule'
2>  GameEd.generated.cpp
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\Game\Source\Game\Private\GameDataManager.cpp(26): warning C4457: declaration of 'ID' hides function parameter
2>  B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\Game\Source\Game\Private\GameDataManager.cpp(19): note: see declaration of 'ID'
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUI\Source\GameUI\Private\GameUIPrivatePCH.h(15): fatal error C1083: Cannot open include file: 'GameModule.h': No such file or directory
2>  Module.GameEd.cpp
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\Game\Source\Game\Private\GameUtil.cpp(8): fatal error C1083: Cannot open include file: 'Interfaces/IImageWrapperModule.h': No such file or directory
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUIEd\Source\GameUIEd\Private\GUIWidgetFactory.cpp(6): fatal error C1083: Cannot open include file: 'WidgetBlueprint.h': No such file or directory
2>B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameEd\Source\GameEd\Private/GameEdPrivatePCH.h(9): fatal error C1083: Cannot open include file: 'ClassViewerModule.h': No such file or directory
2>b:\helical games\repositories\cmdraceholocomics\plugins\gameed\source\gameed\private\GameEdPrivatePCH.h(9): fatal error C1083: Cannot open include file: 'ClassViewerModule.h': No such file or directory
2>ERROR : UBT error : Failed to produce item: B:\Helical Games\repositories\CmdrAceHoloComics\Plugins\GameUI\Binaries\Win64\UE4Editor-GameUI.pdb
2>  Total build time: 55.82 seconds`

**Comment by fathurahman** [comment]
Hello,

I haven't updated this game modules for a long time, there are a lot of
changes to the modules that I forgot what the one in github was, but from
seeing the errors that you send me I assume you forgot to add the required
modules in the dependency list in the build.cs, for example the error that
said undefined type UPackage would easily be resolved by adding "Core" and
"CoreUObject" in the dependency module names.

Thanks,
Fathur
